#!/bin/bash

set -e

VITRO_DB=${1}
VITRO_DB_USERNAME=${2}
VITRO_DB_PASSWORD=${3}
MYSQL_ADMIN_USER=${4}
MYSQL_ADMIN_PASSWORD=${5}

echo "DROP DATABASE IF EXISTS ${VITRO_DB}; CREATE DATABASE IF NOT EXISTS ${VITRO_DB}; GRANT ALL PRIVILEGES ON ${VITRO_DB}.* TO ${VITRO_DB_USERNAME}@localhost IDENTIFIED BY '${VITRO_DB_PASSWORD}';" | mysql --user=${MYSQL_ADMIN_USER} --password=${MYSQL_ADMIN_PASSWORD}
